### PR TITLE
Recognize [] for alternate versions

### PR DESCRIPTION
**Pull request by jose-pr**
Make the following format a valid one for alternate versions.
title[version]
title [version]
title [version][codec][extras]

### CODE REVIEW

**Comment by LukePulverenti** [comment]
@jose-pr I've added a failing test case reported by a user. If you have a moment and want to take this on, I think it would be a good one to handle:
https://github.com/MediaBrowser/Emby.Naming/commit/8cd0063e4205e9332bf4113aa90d9a3a55e79514

Thanks.

**Comment by jose-pr** [comment]
@LukePulverenti i dont see the problem arent the two in that sample different versions , is there a link to user report? What should i be lookinng for?

**Comment by LukePulverenti** [comment]
they are different versions but are not detected as such, therefore they end up as different items in emby.

**Comment by jose-pr** [comment]
Fixed had to remove white spaces to do comparison.

**Pull request merged**
